services:
  wordpress:
    build: ../
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WP_DEBUG: ${WP_DEBUG}
      WP_DEBUG_LOG: ${WP_DEBUG_LOG}
      WP_DEBUG_DISPLAY: ${WP_DEBUG_DISPLAY}
    volumes:
      - ../cinar:/var/www/html/wp-content/themes/cinar
      - wordpress_data:/var/www/html/wp-content
    ports:
      - "8080:80"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
#      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
#    ports:
#      - "3306:3306"
#    networks:
#      - wordpress-network
#
#networks:
#  wordpress-network:
#    driver: bridge

volumes:
  wordpress_data:
  db_data: